### ISSUE TITLE
wrong example on npmjs.com usage

### ISSUE THREAD

**Issue by soulne4ny** [alekzonder/log4js-nested#1]
https://www.npmjs.com/package/log4js-nested#usage

There should be `getLogger` in the following lines as in https://github.com/alekzonder/log4js-nested/blob/master/examples/simple.js

```
var nextLogger = mainLogger.info('next');
var deeperLogger = nextLevelLogger.info('deeper');
```

Otherwise it is quite confusing.

**Comment by alekzonder** [comment]
@soulne4ny thanks!
